import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HelloTest from '../components/HelloTest'
import CheckBoxWithLabel from '../components/CheckBoxWithLabel'
import SimpleCounter from '../components/SimpleCounter'
import IsLoggedIn from '../components/IsLoggedIn'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Testing Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HelloTest />
        <CheckBoxWithLabel />
        <SimpleCounter />
        <IsLoggedIn />
      </main>
    </div>
  )
}
