import '../styles/globals.scss'
import type { AppProps } from 'next/app'
import NavBar from '../components/menu/NavBar'
import Footer from '../components/footer/Footer'
import Head from 'next/head'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
     <Head>
        <title>Z Suite Marketing Demo Page </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
      </Head>

      <NavBar />
      <Component {...pageProps} />
      <Footer />
    </>
  )

}
export default MyApp
